# Generated by Django 4.1 on 2022-08-30 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenyieldzapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.CreateModel(
            name='Gardener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='gardener',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gardenyieldzapi.gardener'),
            preserve_default=False,
        ),
    ]
